pipeline {
    agent any // 不指定執行 agent
    stages { // 開始宣告 Pipeline 流程
        stage("Check www.example.com response code") {
            // 行為宣告
            steps {
                withCredentials([string(credentialsId: 'jenkins_practice_test', variable: 'TOKEN')]){
                    withCredentials([string(credentialsId: 'jenkins_practice_test_notification_group', variable: 'GROUP_ID')]){
						sh '''
							command=$(curl -o /dev/null -s -w %{http_code} www.example.com)
                            
                            if [ "${command}" != "200" ]; then
                            message="www.example.com response code != 200."
                            curl -X GET "https://api.telegram.org/bot${TOKEN}/sendMessage" \
                                -d "chat_id=${GROUP_ID}&text=${message}"
                            fi                
                        '''
                    }
                }
            }
        }
    }
}
